//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnEnglish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatBotNoiDung
    {
        public int MaChat { get; set; }
        public string CauHoiMau { get; set; }
        public string TuKhoa { get; set; }
        public string CauTraLoi { get; set; }
    }
}
