//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnEnglish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemSo
    {
        public int IDHocVien { get; set; }
        public int IDLopHoc { get; set; }
        public Nullable<decimal> DiemNghe { get; set; }
        public Nullable<decimal> DiemNoi { get; set; }
        public Nullable<decimal> DiemDoc { get; set; }
        public Nullable<decimal> DiemViet { get; set; }
        public Nullable<decimal> TongDiem { get; set; }
    
        public virtual HocVienLopHoc HocVienLopHoc { get; set; }
    }
}
