//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnEnglish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemTOEIC
    {
        public int IDHocVien { get; set; }
        public string IDLopHoc { get; set; }
        public Nullable<int> Part1 { get; set; }
        public Nullable<int> Part2 { get; set; }
        public Nullable<int> Part3 { get; set; }
        public Nullable<int> Part4 { get; set; }
        public Nullable<int> DiemNghe { get; set; }
        public Nullable<int> Part5 { get; set; }
        public Nullable<int> Part6 { get; set; }
        public Nullable<int> Part7 { get; set; }
        public Nullable<int> DiemDoc { get; set; }
        public Nullable<int> DiemNoi { get; set; }
        public Nullable<int> DiemViet { get; set; }
        public Nullable<int> TongDiem { get; set; }
    
        public virtual HocVienLopHoc HocVienLopHoc { get; set; }
    }
}
