//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnEnglish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDichVNPAY
    {
        public int IDGiaoDich { get; set; }
        public Nullable<int> IDThanhToan { get; set; }
        public string MaGiaoDich { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string TrangThai { get; set; }
        public string NoiDung { get; set; }
        public string PhanHoiVNPAY { get; set; }
    
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
