//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnEnglish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.HocVienLopHocs = new HashSet<HocVienLopHoc>();
            this.ThanhToans = new HashSet<ThanhToan>();
            this.ThongBaos = new HashSet<ThongBao>();
        }
    
        public string IDLopHoc { get; set; }
        public Nullable<int> IDPhongHoc { get; set; }
        public string IDKhoaHoc { get; set; }
        public Nullable<int> IDGiangVien { get; set; }
        public string TenLop { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> Slot { get; set; }
        public string ThuTrongTuan { get; set; }
        public Nullable<System.TimeSpan> GioHocBD { get; set; }
        public Nullable<System.TimeSpan> GioHocKT { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocVienLopHoc> HocVienLopHocs { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
    }
}
