//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnEnglish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        public int IDTaiLieu { get; set; }
        public string IDKhoaHoc { get; set; }
        public string TenTaiLieu { get; set; }
        public string FileURL { get; set; }
    
        public virtual KhoaHoc KhoaHoc { get; set; }
    }
}
